# DEFAULT VALUES FOR MYSQL DATABASE update later!!
Database:
  hostname: grubnest.com
  port: 3306
  database: s4_grubnest
  username: u4_xb6o263UWu
  password: Sf^R4vzWq6nKl!av!u+JTo81
  minimumConnections: 5
  maximumConnections: 10
  connectionTimeout: 5000